# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  format:
    vars:
      INPUT_FILES:
        sh:
          git ls-files | egrep
          '\.json$|\.html$|\.css|\.js|\.mjs|\.ts|\.tsx|\.astro$|\.md$'
    cmds:
      - node_modules/.bin/prettier --write "{{.JS_FILES}}"
