# https://taskfile.dev

version: "3"

vars:
  PROJECT_ROOT:
    sh: pwd
  MANIFEST_JSON:
    sh: cat ./etc/manifest.json
  MANIFEST:
    ref: "fromJson .MANIFEST_JSON"
  PRETTIER_TARGETS:
    sh: git ls-files | egrep '\.astro$|\.md$'

tasks:
  build-vite:
    internal: true
    cmds:
      - for: { var: MANIFEST }
        silent: true
        cmd: |
          if [[ '{{.ITEM.builder}}' == 'vite' ]]; then
            cd {{.ITEM.src}}
            node_modules/.bin/vite build --base={{.ITEM.publicPath}}
            rm -rf "{{.PROJECT_ROOT}}/dist/{{.ITEM.publicPath}}"
            mv dist "{{.PROJECT_ROOT}}/dist/{{.ITEM.publicPath}}"
          fi

  build-astro:
    cmds:
      - cd packages/www && pnpm build && cp -R dist/ {{.PROJECT_ROOT}}/dist

  build:
    cmds:
      - cmd: mkdir -p dist
      - task: build-astro
      - task: build-vite

  dev:
    env:
      PROJECT_ROOT: '{{.PROJECT_ROOT}}'
    cmds:
      - cmd: caddy run

  test-jest:
    internal: true
    vars:
      DIR: '{{default "." .DIR}}'
    cmds:
      - cmd: cd {{.DIR}} && node_modules/.bin/jest test

  test:
    cmds:
      - task: test-jest
        vars: { DIR: "./packages/lox-interpreter" }

  format:
    cmds:
      - cmd: node_modules/.bin/prettier --write .
        silent: true
      - for: { var: PRETTIER_TARGETS, split: "\n" }
        cmd: node_modules/.bin/prettier --write {{ .ITEM }}
        silent: true

  format-check:
    cmds:
      - cmd: node_modules/.bin/prettier --check .
        silent: true
      - for: { var: PRETTIER_TARGETS, split: "\n" }
        cmd: node_modules/.bin/prettier --check {{ .ITEM }}
        silent: true
