# https://taskfile.dev

version: "3"

tasks:
  format:
    vars:
      PRETTIER_TARGETS:
        sh: git ls-files | egrep '\.astro$|\.md$'
    cmds:
      - cmd: node_modules/.bin/prettier --write .
        silent: true
      - for: { var: PRETTIER_TARGETS, split: "\n" }
        cmd: node_modules/.bin/prettier --write {{ .ITEM }}
        silent: true
