name: Main CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - run: |
          NODE_VERSION=$(cat package.json | jq -r '.volta.node')
          volta install "node@${NODE_VERSION}"
          volta install corepack@latest
          corepack enable --install-directory "$VOLTA_HOME/bin"
      - run: pnpm install
      - run: pnpm format:check
